server:
  port: 80
  error:
    include-stacktrace: never
  servlet.context-path: /api/v1/users
  
spring:
  application:
    name: Accounts App
  jpa:
    show-sql: false
    generate-ddl: false
    database: default
    hibernate:
      ddl-auto: update
      
